import '../styles/globals.css'; 
import Footer from './components/Footer';
import NavBar from './components/NavBar'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
      <NavBar />
        {children}
      <Footer/> 
      </body>
    </html>
  )
}
